### ISSUE TITLE
[Bug] Multiple node-controllers can remove the wrong pods.

### ISSUE THREAD

**Issue by BobVanB** [netscaler/netscaler-k8s-node-controller#41]
# Issue

When running 2 nodes-controllers on the same cluster, it is maybe possible for a node-controller to delete the wrong router.

When having these 2 router names:

1. mytest-kube-cnc-router-...
2. test-kube-cnc-router-...

The node-controller that contains the second one can delete the first one.

## Setup

Helm chart used: citrix/citrix-node-controller 2.2.11
Container used: quay.io/citrix/citrix-k8s-node-controller:2.2.1

## Location

```go
// vendor/kube.router/delete.go
func (api *KubernetesAPIServer) DeletePods() {
  ..
  for i := 0; i < len(pods.Items); i++ {
    if strings.Contains(pods.Items[i].Name, configMapName) {
```

## Possible solution

Check the prefix

```go
// vendor/kube.router/delete.go
func (api *KubernetesAPIServer) DeletePods() {
  ..
  for i := 0; i < len(pods.Items); i++ {
    if strings.HasPrefix(pods.Items[i].Name, configMapName) {
```

**Comment by subashd** [comment]
This is fixed in version 2.2.12
