### ISSUE TITLE
[Bug] The routers are recreated every 9m, with connection loss as one of the results

### ISSUE THREAD

**Issue by BobVanB** [netscaler/netscaler-k8s-node-controller#42]
# Issue

Every 9m or so we noticed that the `kube-cnc-router` configmap is destroyed and that all the `kube-cnc-router` are recreated.

This is what it ends up in:

1. The node-controller creates new kube-cnc-routers with new IP addresses from the vxlan.
2. This information is then updated in the citrix adc.
3. This will temporarily break the connection with the current worker.

## Setup

Helm chart used: citrix/citrix-node-controller 2.2.11
Container used: quay.io/citrix/citrix-k8s-node-controller:2.2.1

## Expected behavior

There are no changes and the node-controller should not recreated the `kube-cnc-router`.

## What is happening

1. The configmap watcher is triggering a `update` event for the configmap `citrix-node-controller`
    ```go
    // citrix-node-controller/cmd/citrix-node-controller/k8sInterface.go
    func ConfigMapInputWatcher(api *router.KubernetesAPIServer, IngressDeviceClient *NitroClient, ControllerInputObj *ControllerInput, CncNamespace string) {
     klog.Infof("[INFO] Starting configmap watcher in namespace: %v", CncNamespace)
     ConfigMapWatcher := cache.NewListWatchFromClient(api.Client.Core().RESTClient(), "configmaps", CncNamespace, fields.Everything())
      _, configcontroller := cache.NewInformer(ConfigMapWatcher, &v1.ConfigMap{}, 0, cache.ResourceEventHandlerFuncs{ 
        UpdateFunc: func(obj interface{}, newobj interface{}) {
          HandleConfigMapUpdateEvent(obj, newobj, IngressDeviceClient, ControllerInputObj)
        },
    ```
2. The configmap `citrix-node-controller` has not changed, the `resourceVersion` of both previous and new object are the same.
3. This will trigger `router.CreatePodsCmap()` in `HandleConfigMapUpdateEvent`, because the names are the same.
   ```go
   func HandleConfigMapUpdateEvent(obj interface{}, newobj interface{}, IngressDeviceClient *NitroClient, ControllerInputObj *ControllerInput) {
     MetaData := obj.(*v1.ConfigMap).ObjectMeta
     if _, ok := ConfigMapDataNew["EndpointIP"]; ok {
       ...
     } else if MetaData.Name == ControllerInputObj.ConfigMap {
       //In else condition; input.Configmap update event is processed, this configmap is user provided which contains toleration to added on kube-cnc-router pods.
       klog.Infof("[INFO] Received %v cmap update event", ControllerInputObj.ConfigMap)
       router.CreatePodsCmap()
     }
   }
   ```
4.  `router.CreatePodsCmap()` will lead to a new configmap and new event listener for nodes.
   ```go
   // vendor/kube.router/create.go
   func CreatePodsCmap() {
     err := k8sclient.CreateK8sConfigMap(input)  // this will delete the current configmap
     k8sclient.ReadCNCConfigMap(input)
     WatchNodeEvents(k8sclient, input)  // this will recreate everything
   ```
6. CreateK8sConfigMap contains a delete configmap!
   ```go
   // vendor/kube.router/create.go
   func (api *KubernetesAPIServer) CreateK8sConfigMap(input *Input) error {
     ...
     api.Client.CoreV1().ConfigMaps(input.NameSpace).Delete(configMapName, metav1.NewDeleteOptions(0))
   ```
7. After that the new node event listener will trigger new events to recreate the pods with new addresses in there pod.
8. The first log entry you see after this, because the configmap has been replaced:
   ```log
   W0914 07:47:18.130972       1 reflector.go:303] citrix-node-controller/cmd/citrix-node-controller/k8sInterface.go:124: watch of *v1.ConfigMap ended with: too old resource version: 557927642 (557933255)
   ```

## Possible workaround 1#

Do not use the node-controller configmap, this way the event is never triggered.
And thus do not use tainted nodes in a cluster.

## Possible workaround 2#

This is a workaround not a possible solution, but this will stop the recreation of the pods when there are no changes in configmap `citrix-node-controller`
Add a `resourceVersion` check

```go
func HandleConfigMapUpdateEvent(obj interface{}, newobj interface{}, IngressDeviceClient *NitroClient, ControllerInputObj *ControllerInput) {
  MetaDataNew := newobj.(*v1.ConfigMap).ObjectMeta
  MetaData := obj.(*v1.ConfigMap).ObjectMeta
  if _, ok := ConfigMapDataNew["EndpointIP"]; ok {
    ...
  } else if MetaData.Name == ControllerInputObj.ConfigMap {
    if MetaData.ResourceVersion == MetaDataNew.ResourceVersion {
      klog.Infof("[DEBUG] Failed to detect no changes for %v cmap update event.", ControllerInputObj.ConfigMap)
    } else {
      klog.Infof("[INFO] Received %v cmap update event", ControllerInputObj.ConfigMap)
      router.CreatePodsCmap()
    }
  }
}
```

## Possible solutions

Use the current router config map to update the internal state.
Don't delete it, but validate its contents and reuse its content.

Benefits that can come from this:

* the router can be destroyed and recreated with the same address
* the node controller can restart without changing current routers
* possible updates of the node controller without changing current routers

## More thoughs

I have no evidence to why the configmap watcher a updateevent triggers.
My suspect for now is: https://github.com/kubernetes/client-go/blob/master/tools/cache/controller.go#L348
And that kubernetes will always send a update event for all resources currently in the watch.
As a result you can't use this event for a workflow where you start from scratch:

This two should differentiate:

* Starting a app 
  ```go
  // cmd/citrix-node-controller/main.go
  func InitCitrixNodeControllerPods() {
     router.CreateK8sApiserverClient()
     router.DeletePodsCmap()
     router.CreatePodsCmap()
   }
   ```
* Update events during watch

**Comment by subashd** [comment]
This is fixed in version 2.2.12
